### ISSUE TITLE
The Rearrange of einops.layers.torch has an error: *** AttributeError: 'Rearrange' object has no attribute 'recipe'

### ISSUE THREAD

**Issue by yibingchen2023** [pashtari/factorizer#2]
When I run the code below:
sw_matricize = ft.SWMatricize((None, 32, 128, 128, 128), head_dim=8, patch_size=8)

An occur happened as below:
*** AttributeError: 'Rearrange' object has no attribute 'recipe'

Is the version of einops (i.e., 0.7.0) in my computer not suitable?

**Comment by pashtari** [comment]
Hi, thanks for pointing that out! You're right; the issue is because of the changes in the `einops` package. In previous versions, `Rearrange` had the `recipe` attribute. I've rewrote and modified parts of the `ft.Reshape` base module to work without it. So, `ft.SWMatricize` should be good now.  For the fix, just uninstall and then reinstall `factorizer`. That should sort it out. 👍  Let me know if you run into any more issues!  Cheers!

**Comment by yibingchen2023** [comment]
Very thanks for your changing! No error occurred, everything is fine now. Thanks a lot.
