### ISSUE TITLE
SegmentationFactorizer's code is incomplete

### ISSUE THREAD

**Issue by lsnls** [pashtari/factorizer#3]
Hi,
in the SegmentationFactorizer class, UNet's __init__ method is just called, but UNet's forward() method doesn't seem to be overridden.

**Comment by pashtari** [comment]
Hi, thanks for identifying this glitch! The issue occurred after updating to version 0.0.2 and is now fixed by passing `kwargs` from `SegmentationFactorizer` to `FactorizerStage`. The updated version is now in the repository. Please test it and let me know if it solves the problem. Appreciate your help!

**Comment by TOIS-2025** [comment]
Hi, Thanks for your reply. As shown in the image, is `decoder_block` variable missing from the `factorizer.py`?
![O}CE~Q{RY4 (PJ(MUB`URKI](https://github.com/pashtari/factorizer/assets/87290660/a549e619-106e-45ba-8139-46530b054dad)

**Comment by pashtari** [comment]
Hi! That's right; there's still a typo here. It's now corrected from `encoder_block = num_decoder_stages * [(FactorizerStage, kwargs)]` to `decoder_block = num_decoder_stages * [(FactorizerStage, kwargs)]` and from `block = encoder_block + bottleneck_block + encoder_block' to `block = encoder_block + bottleneck_block + decoder_block` in the code. The repo is now updated. I'll soon test version 0.0.2 and provide MONAI bundles for replicating the initial version's results. Again, your help is much appreciated!
